apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykefravarsstatistikk-api
  namespace: default
  labels:
    team: teamtag
spec:
  image: navikt/sykefravarsstatistikk-api:{{version}}
  team: teamtag
  port: 8080
  ingresses:
    - https://arbeidsgiver.nais.adeo.no/sykefravarsstatistikk-api/
  liveness:
    path: /sykefravarsstatistikk-api/internal/healthcheck
    initialDelay: 20
  readiness:
    path: /sykefravarsstatistikk-api/internal/healthcheck
    initialDelay: 20
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
  prometheus:
    enabled: true
    path: /sykefravarsstatistikk-api/internal/actuator/prometheus
  vault:
    enabled: true