spring:
  config.activate.on-profile: local
  h2.console:
    enabled: true
    path: /h2

wiremock.mock:
  port: 8081

altinn:
  url: "http://localhost:${wiremock.mock.port}/altinn/"
  apikey: "test"
  apigw.apikey: "test"
  proxy:
    url: "http://localhost:${wiremock.mock.port}/altinn-rettigheter-proxy/"
  iaweb.service:
    code: 3403
    edition: 1

enhetsregisteret:
  url: "http://localhost:${wiremock.mock.port}/enhetsregisteret"


statistikk.importering.aktivert: true
statistikk.eksportering.aktivert: true

applikasjon.datasource:
  url: jdbc:h2:mem:db-local;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
  username: SA
  password:
  driver-class-name: org.h2.Driver

datavarehus.datasource:
  url: jdbc:h2:mem:db-local;MODE=Oracle;DB_CLOSE_DELAY=-1
  username: SA
  password:
  driver-class-name: org.h2.Driver

nais.cluster.name: local

kafka:
  outbound:
    bootstrapServers: localhost:9092
    securityProtocol: PLAINTEXT

no.nav.security.jwt:
  issuer:
    tokenx:
      discoveryurl: https://fakedings.dev-gcp.nais.io/fake/.well-known/oauth-authorization-server
      accepted_audience: dev-fss:arbeidsgiver:sykefravarsstatistikk-api
    selvbetjening:
      discoveryurl: http://localhost:${mock-oauth2-server.port}/selvbetjening/.well-known/openid-configuration
      accepted_audience: someaudience
      cookie_name: selvbetjening-idtoken

tokenxclient:
  jwk: '
    {
      "kty": "RSA",
      "d": "BRcX3ywynvH9WA5wOz_vU9HzSY6OkmRKOGGqLEG_fEtVcXwxReSSuVcXZUngZrPkoC3li-jvNfDz9c_7WP44HkO07RkG10mSspLjS-EarYg5HUI8JPfrjtacCVmq0pnVlvEeR-35x1e91o6iC5-hEGQPkBgImKwuFy1u2eiPBM-mIoNHOSpO5IqHBAP2Gi2w7SU28mZ1xt2xmvj6kGE96u3G6nSkr175tgdi0tHO9T7BCYFjr1NNkLojzExpo5gUVyNsm17ahMi2XE7NIRdduHkEXcprr5DayDK7_VaQYqa3OPsN3UcRZanXcpdFt9HHt8KyuRW3zvXJ6-AtM1UCkQ",
      "e": "AQAB",
      "use": "sig",
      "kid": "1",
      "n": "ssXDjDMHXWxvnAFXwJiKqgyf6tn_zHGbkSiWNgHZ2xsQgxo-gzv5JssbJxLCDZCdC5zX7nXIHOC5fid_fxMXGNAYh6xaJzxSLGGAJHSp_uCh5zSPAGFigihxLNwwWaDxYDcLFC9QHzaV__BaB_JUaHyD7aFDUEyQiB4MXAqTkCEUmPj-RTiUbcnicD5Q32zByJ8gzG3ufxuCGnP-xcc5QJQ8TmrlLgNzgiHHdkpRjeXCHovP_gYGXujJkhQ0dvgYtVpgoHeGcH1FC9ZRd6IiFtanJ1MPwg2i6sR_HlE2l3Ua_Knj4FZY3F0cM3P4AgXI8TyEhQgM2GWwPGf6YNrHyQ"
    }'
  clientId: dev-fss:arbeidsgiver:sykefravarsstatistikk-api
  altinn_rettigheter_proxy_audience: dev-gcp:arbeidsgiver:altinn-rettigheter-proxy

