-- Tabeller fra datavarehus
create schema dt_p;

create table dt_p.V_DIM_IA_SEKTOR
(
    SEKTORKODE CHAR(1),
    SEKTORNAVN VARCHAR(60)
);

create table dt_p.V_DIM_IA_FGRP_NARING_SN2007
(
    NARGRPKODE CHAR(2) NOT NULL,
    NARGRPNAVN VARCHAR(60) NOT NULL,
    PRIMARY KEY (NARGRPKODE)
);

create table dt_p.V_DIM_IA_NARING_SN2007
(
    NARINGKODE CHAR(2) NOT NULL,
    NARGRPKODE CHAR(2) NOT NULL,
    NARINGNAVN VARCHAR(100) NOT NULL,
    CONSTRAINT r1_naring_sn2007_pk PRIMARY KEY (NARINGKODE)
);

create table dt_p.V_AGG_IA_SYKEFRAVAR_LAND
(
     ARSTALL CHAR(4) NOT NULL,
     KVARTAL CHAR(1) NOT NULL,
     NARING CHAR(2) NOT NULL,
     NARINGNAVN VARCHAR(60),
     ALDER CHAR(1) NOT NULL,
     KJONN CHAR(1) NOT NULL,
     FYLKBO CHAR(2) NOT NULL,
     FYLKNAVN VARCHAR(35),
     VARIGHET CHAR(1) NOT NULL,
     SEKTOR CHAR(1) NOT NULL,
     SEKTORNAVN VARCHAR(60),
     TAPTEDV DECIMAL(14,6),
     MULIGEDV DECIMAL(15,6),
     ANTPERS DECIMAL(7,0),
     IA1_TAPTEDV DECIMAL(14,6),
     IA1_MULIGEDV DECIMAL(15,6),
     IA1_ANTPERS DECIMAL(7,0),
     IA2_TAPTEDV DECIMAL(14,6),
     IA2_MULIGEDV DECIMAL(15,6),
     IA2_ANTPERS DECIMAL(7,0),
     IA3_TAPTEDV DECIMAL(14,6),
     IA3_MULIGEDV DECIMAL(15,6),
     IA3_ANTPERS DECIMAL(7,0)
)