-- Dimensjoner

insert into sektor (kode, navn) values('0', 'Ukjent sektor');
insert into sektor (kode, navn) values('1', 'Statlig forvaltning');
insert into sektor (kode, navn) values('2', 'Kommunal forvaltning');
insert into sektor (kode, navn) values('3', 'Privat og offentlig næringsvirksomhet');
insert into sektor (kode, navn) values('9', 'Fylkeskommunal forvaltning');


insert into naringsgruppe (kode, navn) values('0', 'Ukjent næringskode');
insert into naringsgruppe (kode, navn) values('1', 'Jordbruk, skogbruk og fiske');
insert into naringsgruppe (kode, navn) values('5', 'Bergverksdrift og utvinning');
insert into naringsgruppe (kode, navn) values('10', 'Industri');
insert into naringsgruppe (kode, navn) values('35', 'Elektrisitet-, vann og renovasjon');
insert into naringsgruppe (kode, navn) values('41', 'Bygge- og anleggsvirksomhet');
insert into naringsgruppe (kode, navn) values('45', 'Varehandel, reparasjon av motorvogner');
insert into naringsgruppe (kode, navn) values('49', 'Transport og lagring');
insert into naringsgruppe (kode, navn) values('55', 'Overnattings- og serveringsvirksomhet');
insert into naringsgruppe (kode, navn) values('58', 'Informasjon og kommunikasjon');
insert into naringsgruppe (kode, navn) values('64', 'Finansierings- og forsikringsvirksomhet');
insert into naringsgruppe (kode, navn) values('68', 'Omsetning og drift av fast eiendom');
insert into naringsgruppe (kode, navn) values('69', 'Faglig, vitenskapelig og teknisk tjenesteyting');
insert into naringsgruppe (kode, navn) values('77', 'Forretningsmessig tjenesteyting');
insert into naringsgruppe (kode, navn) values('84', 'Off. adm., forsvar, sosialforsikring');
insert into naringsgruppe (kode, navn) values('85', 'Undervisning');
insert into naringsgruppe (kode, navn) values('86', 'Helse- og sosialtjenester');
insert into naringsgruppe (kode, navn) values('90', 'Private tjenester ellers');


insert into naring (kode, naringsgruppe_kode, navn) values ('00', '0','Ukjent næringskode');
insert into naring (kode, naringsgruppe_kode, navn) values ('01', '1','Jordbruk og tjenester tilknyttet jordbruk, jakt og viltstell');
insert into naring (kode, naringsgruppe_kode, navn) values ('02', '1','Skogbruk og tjenester tilknyttet skogbruk');
insert into naring (kode, naringsgruppe_kode, navn) values ('03', '1','Fiske, fangst og akvakultur');
insert into naring (kode, naringsgruppe_kode, navn) values ('05', '5','Bryting av steinkull og brunkull');
insert into naring (kode, naringsgruppe_kode, navn) values ('06', '5','Utvinning av råolje og naturgass');
insert into naring (kode, naringsgruppe_kode, navn) values ('07', '5','Bryting av metallholdig malm');
insert into naring (kode, naringsgruppe_kode, navn) values ('08', '5','Bryting og bergverksdrift ellers');
insert into naring (kode, naringsgruppe_kode, navn) values ('09', '5','Tjenester tilknyttet bergverksdrift og utvinning');
insert into naring (kode, naringsgruppe_kode, navn) values ('10', '10', 'Produksjon av nærings- og nytelsesmidler');
insert into naring (kode, naringsgruppe_kode, navn) values ('11', '10', 'Produksjon av drikkevarer');
insert into naring (kode, naringsgruppe_kode, navn) values ('12', '10', 'Produksjon av tobakksvarer');
insert into naring (kode, naringsgruppe_kode, navn) values ('13', '10', 'Produksjon av tekstiler');
insert into naring (kode, naringsgruppe_kode, navn) values ('14', '10', 'Produksjon av klær');
insert into naring (kode, naringsgruppe_kode, navn) values ('15', '10', 'Produksjon av lær og lærvarer');
insert into naring (kode, naringsgruppe_kode, navn) values ('16', '10', 'Produksjon av trelast og varer av tre, kork, strå og flettematerialer, unntatt møbler');
insert into naring (kode, naringsgruppe_kode, navn) values ('17', '10', 'Produksjon av papir og papirvarer');
insert into naring (kode, naringsgruppe_kode, navn) values ('18', '10', 'Trykking og reproduksjon av innspilte opptak');
insert into naring (kode, naringsgruppe_kode, navn) values ('19', '10', 'Produksjon av kull- og raffinerte petroleumsprodukter');
insert into naring (kode, naringsgruppe_kode, navn) values ('20', '10', 'Produksjon av kjemikalier og kjemiske produkter');
insert into naring (kode, naringsgruppe_kode, navn) values ('21', '10', 'Produksjon av farmasøytiske råvarer og preparater');
insert into naring (kode, naringsgruppe_kode, navn) values ('22', '10', 'Produksjon av gummi- og plastprodukter');
insert into naring (kode, naringsgruppe_kode, navn) values ('23', '10', 'Produksjon av andre ikke-metallholdige mineralprodukter');
insert into naring (kode, naringsgruppe_kode, navn) values ('24', '10', 'Produksjon av metaller');
insert into naring (kode, naringsgruppe_kode, navn) values ('25', '10', 'Produksjon av metallvarer, unntatt maskiner og utstyr');
insert into naring (kode, naringsgruppe_kode, navn) values ('26', '10', 'Produksjon av datamaskiner og elektroniske og optiske produkter');
insert into naring (kode, naringsgruppe_kode, navn) values ('27', '10', 'Produksjon av elektrisk utstyr');
insert into naring (kode, naringsgruppe_kode, navn) values ('28', '10', 'Produksjon av maskiner og utstyr til generell bruk, ikke nevnt annet sted');
insert into naring (kode, naringsgruppe_kode, navn) values ('29', '10', 'Produksjon av motorvogner og tilhengere');
insert into naring (kode, naringsgruppe_kode, navn) values ('30', '10', 'Produksjon av andre transportmidler');
insert into naring (kode, naringsgruppe_kode, navn) values ('31', '10', 'Produksjon av møbler');
insert into naring (kode, naringsgruppe_kode, navn) values ('32', '10', 'Annen industriproduksjon');
insert into naring (kode, naringsgruppe_kode, navn) values ('33', '10', 'Reparasjon og installasjon av maskiner og utstyr');
insert into naring (kode, naringsgruppe_kode, navn) values ('35', '35', 'Elektrisitets-, gass-, damp- og varmtvannsforsyning');
insert into naring (kode, naringsgruppe_kode, navn) values ('36', '35', 'Uttak fra kilde, rensing og distribusjon av vann');
insert into naring (kode, naringsgruppe_kode, navn) values ('37', '35', 'Oppsamling og behandling av avløpsvann');
insert into naring (kode, naringsgruppe_kode, navn) values ('38', '35', 'Innsamling, behandling, disponering og gjenvinning av avfall');
insert into naring (kode, naringsgruppe_kode, navn) values ('39', '35', 'Miljørydding, miljørensing og lignende virksomhet');
insert into naring (kode, naringsgruppe_kode, navn) values ('41', '41', 'Oppføring av bygninger');
insert into naring (kode, naringsgruppe_kode, navn) values ('42', '41', 'Anleggsvirksomhet');
insert into naring (kode, naringsgruppe_kode, navn) values ('43', '41', 'Spesialisert bygge- og anleggsvirksomhet');
insert into naring (kode, naringsgruppe_kode, navn) values ('45', '45', 'Handel med og reparasjon av motorvogner');
insert into naring (kode, naringsgruppe_kode, navn) values ('46', '45', 'Agentur- og engroshandel, unntatt med motorvogner');
insert into naring (kode, naringsgruppe_kode, navn) values ('47', '45', 'Detaljhandel, unntatt med motorvogner');
insert into naring (kode, naringsgruppe_kode, navn) values ('49', '49', 'Landtransport og rørtransport');
insert into naring (kode, naringsgruppe_kode, navn) values ('50', '49', 'Sjøfart');
insert into naring (kode, naringsgruppe_kode, navn) values ('51', '49', 'Lufttransport');
insert into naring (kode, naringsgruppe_kode, navn) values ('52', '49', 'Lagring og andre tjenester tilknyttet transport');
insert into naring (kode, naringsgruppe_kode, navn) values ('53', '49', 'Post og distribusjonsvirksomhet');
insert into naring (kode, naringsgruppe_kode, navn) values ('55', '55', 'Overnattingsvirksomhet');
insert into naring (kode, naringsgruppe_kode, navn) values ('56', '55', 'Serveringsvirksomhet');
insert into naring (kode, naringsgruppe_kode, navn) values ('58', '58', 'Forlagsvirksomhet');
insert into naring (kode, naringsgruppe_kode, navn) values ('59', '58', 'Film-, video- og fjernsynsprogramproduksjon, utgivelse av musikk- og lydopptak');
insert into naring (kode, naringsgruppe_kode, navn) values ('60', '58', 'Radio- og fjernsynskringkasting');
insert into naring (kode, naringsgruppe_kode, navn) values ('61', '58', 'Telekommunikasjon');
insert into naring (kode, naringsgruppe_kode, navn) values ('62', '58', 'Tjenester tilknyttet informasjonsteknologi');
insert into naring (kode, naringsgruppe_kode, navn) values ('63', '58', 'Informasjonstjenester');
insert into naring (kode, naringsgruppe_kode, navn) values ('64', '64', 'Finansieringsvirksomhet');
insert into naring (kode, naringsgruppe_kode, navn) values ('65', '64', 'Forsikringsvirksomhet og pensjonskasser, unntatt trygdeordninger underlagt offentlig forvaltning');
insert into naring (kode, naringsgruppe_kode, navn) values ('66', '64', 'Tjenester tilknyttet finansierings- og forsikringsvirksomhet');
insert into naring (kode, naringsgruppe_kode, navn) values ('68', '68', 'Omsetning og drift av fast eiendom');
insert into naring (kode, naringsgruppe_kode, navn) values ('69', '69', 'Juridisk og regnskapsmessig tjenesteyting');
insert into naring (kode, naringsgruppe_kode, navn) values ('70', '69', 'Hovedkontortjenester, administrativ rådgivning');
insert into naring (kode, naringsgruppe_kode, navn) values ('71', '69', 'Arkitektvirksomhet og teknisk konsulentvirksomhet, og teknisk prøving og analyse');
insert into naring (kode, naringsgruppe_kode, navn) values ('72', '69', 'Forskning og utviklingsarbeid');
insert into naring (kode, naringsgruppe_kode, navn) values ('73', '69', 'Annonse- og reklamevirksomhet og markedsundersøkelser');
insert into naring (kode, naringsgruppe_kode, navn) values ('74', '69', 'Annen faglig, vitenskapelig og teknisk virksomhet');
insert into naring (kode, naringsgruppe_kode, navn) values ('75', '69', 'Veterinærtjenester');
insert into naring (kode, naringsgruppe_kode, navn) values ('77', '77', 'Utleie- og leasingvirksomhet');
insert into naring (kode, naringsgruppe_kode, navn) values ('78', '77', 'Arbeidskrafttjenester');
insert into naring (kode, naringsgruppe_kode, navn) values ('79', '77', 'Reisebyrå- og reisearrangørvirksomhet og tilknyttede tjenester');
insert into naring (kode, naringsgruppe_kode, navn) values ('80', '77', 'Vakttjeneste og etterforsking');
insert into naring (kode, naringsgruppe_kode, navn) values ('81', '77', 'Tjenester tilknyttet eiendomsdrift');
insert into naring (kode, naringsgruppe_kode, navn) values ('82', '77', 'Annen forretningsmessig tjenesteyting');
insert into naring (kode, naringsgruppe_kode, navn) values ('84', '84', 'Offentlig administrasjon og forsvar, og trygdeordninger underlagt offentlig forvaltning');
insert into naring (kode, naringsgruppe_kode, navn) values ('85', '85', 'Undervisning');
insert into naring (kode, naringsgruppe_kode, navn) values ('86', '86', 'Helsetjenester');
insert into naring (kode, naringsgruppe_kode, navn) values ('87', '86', 'Pleie- og omsorgstjenester i institusjon');
insert into naring (kode, naringsgruppe_kode, navn) values ('88', '86', 'Sosiale omsorgstjenester uten botilbud');
insert into naring (kode, naringsgruppe_kode, navn) values ('90', '90', 'Kunstnerisk virksomhet og underholdningsvirksomhet');
insert into naring (kode, naringsgruppe_kode, navn) values ('91', '90', 'Drift av biblioteker, arkiver, museer og annen kulturvirksomhet');
insert into naring (kode, naringsgruppe_kode, navn) values ('92', '90', 'Lotteri og totalisatorspill');
insert into naring (kode, naringsgruppe_kode, navn) values ('93', '90', 'Sports- og fritidsaktiviteter og drift av fornøyelsesetablissementer');
insert into naring (kode, naringsgruppe_kode, navn) values ('94', '90', 'Aktiviteter i medlemsorganisasjoner');
insert into naring (kode, naringsgruppe_kode, navn) values ('95', '90', 'Reparasjon av datamaskiner, husholdningsvarer og varer til personlig bruk');
insert into naring (kode, naringsgruppe_kode, navn) values ('96', '90', 'Annen personlig tjenesteyting');
insert into naring (kode, naringsgruppe_kode, navn) values ('97', '90', 'Lønnet arbeid i private husholdninger');
insert into naring (kode, naringsgruppe_kode, navn) values ('99', '90', 'Internasjonale organisasjoner og organer');

commit