apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sykefravarsstatistikk-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{ image }}
  team: arbeidsgiver
  port: 8080
  ingresses:
    - https://arbeidsgiver.nais.preprod.local/sykefravarsstatistikk-api/
  liveness:
    path: /sykefravarsstatistikk-api/internal/healthcheck
    initialDelay: 30
  readiness:
    path: /sykefravarsstatistikk-api/internal/healthcheck
    initialDelay: 30
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev
  envFrom:
    - configmap: loginservice-idporten
  prometheus:
    enabled: true
    path: /sykefravarsstatistikk-api/internal/actuator/prometheus
  webproxy: true
  vault:
    enabled: true
    paths:
      - kvPath: /kv/preprod/fss/sykefravarsstatistikk-api/arbeidsgiver
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /apikey/apigw/dev/eksternapp.altinn.serviceowner/sykefravarsstatistikk-api_q1
        mountPath: /var/run/secrets/nais.io/altinn
  kafka:
    pool: nav-dev
  resources:
    limits:
      memory: 2048Mi
    requests:
      memory: 1024Mi
