apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sykefravarsstatistikk-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{ image }}
  team: arbeidsgiver
  port: 8080
  ingresses:
    - https://arbeidsgiver.nais.adeo.no/sykefravarsstatistikk-api/
    - https://sykefravarsstatistikk-api.prod-fss-pub.nais.io/
  tokenx:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: sykefravarsstatistikk
          namespace: arbeidsgiver
          cluster: prod-gcp
        - application: min-side-arbeidsgiver
          namespace: fager
          cluster: prod-gcp
        - application: min-ia
          namespace: teamia
          cluster: prod-gcp
        - application: forebyggingsplan-frontend
          namespace: pia
          cluster: prod-gcp
    outbound:
      rules:
        - application: altinn-rettigheter-proxy
          namespace: arbeidsgiver
          cluster: prod-gcp
  liveness:
    path: /sykefravarsstatistikk-api/internal/healthcheck
    initialDelay: 30
  readiness:
    path: /sykefravarsstatistikk-api/internal/healthcheck
    initialDelay: 30
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
  envFrom:
    - configmap: loginservice-idporten
  prometheus:
    enabled: true
    path: /sykefravarsstatistikk-api/internal/actuator/prometheus
  webproxy: true
  vault:
    enabled: true
    paths:
      - kvPath: /kv/prod/fss/sykefravarsstatistikk-api/arbeidsgiver
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /apikey/apigw/prod/eksternapp.altinn.serviceowner/sykefravarsstatistikk-api
        mountPath: /var/run/secrets/nais.io/altinn
  kafka:
    pool: nav-prod
  resources:
    limits:
      memory: 4096Mi
      cpu: 2000m
    requests:
      memory: 2048Mi
      cpu: 1000m
