apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sykefravarsstatistikk-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - https://sykefravarsstatistikk-api.prod-fss-pub.nais.io/ # bro mellom fss og gcp
  tokenx:
    enabled: true
  secureLogs:
    enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: sykefravarsstatistikk
          namespace: arbeidsgiver
          cluster: prod-gcp
        - application: min-side-arbeidsgiver
          namespace: fager
          cluster: prod-gcp
        - application: min-ia
          namespace: teamia
          cluster: prod-gcp
        - application: min-ia
          namespace: pia
          cluster: prod-gcp
        - application: forebyggingsplan-frontend
          namespace: teamia
          cluster: prod-gcp
    outbound:
      rules:
        - application: altinn-rettigheter-proxy
          namespace: arbeidsgiver
          cluster: prod-gcp
      external:
        - host: data.brreg.no
  liveness:
    path: /sykefravarsstatistikk-api/internal/liveness
    initialDelay: 30
  readiness:
    path: /sykefravarsstatistikk-api/internal/readiness
    initialDelay: 30
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
  prometheus:
    enabled: true
    path: /sykefravarsstatistikk-api/internal/actuator/prometheus
  webproxy: true

  envFrom:
    - secret: sykefravarsstatistikk-api

  vault:
    enabled: true

  kafka:
    pool: nav-prod
  resources:
    limits:
      memory: 64Gi
      cpu: 4000m
    requests:
      memory: 500Mi
      cpu: 200m
