apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sykefravarsstatistikk-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{ image }}
  team: arbeidsgiver
  port: 8080
  ingresses:
    - https://arbeidsgiver.nais.adeo.no/sykefravarsstatistikk-api/
  liveness:
    path: /sykefravarsstatistikk-api/internal/healthcheck
    initialDelay: 30
  readiness:
    path: /sykefravarsstatistikk-api/internal/healthcheck
    initialDelay: 30
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
  prometheus:
    enabled: true
    path: /sykefravarsstatistikk-api/internal/actuator/prometheus
  webproxy: true
  vault:
    enabled: true
    paths:
      - kvPath: /kv/prod/fss/sykefravarsstatistikk-api/arbeidsgiver
        mountPath: /var/run/secrets/nais.io/vault
      - kvPath: /apikey/apigw/prod/eksternapp.altinn.serviceowner/sykefravarsstatistikk-api
        mountPath: /var/run/secrets/nais.io/altinn
  resources:
    limits:
      memory: 1024Mi
    requests:
      memory: 512Mi
