apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sykefravarsstatistikk-api
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  image: {{ image }}
  port: 8080
  tokenx:
    enabled: true
  secureLogs:
    enabled: true
  liveness:
    path: /sykefravarsstatistikk-api/internal/liveness
    initialDelay: 30
  readiness:
    path: /sykefravarsstatistikk-api/internal/readiness
    initialDelay: 30
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
  prometheus:
    enabled: true
    path: /sykefravarsstatistikk-api/internal/actuator/prometheus
  webproxy: true

  envFrom:
    - secret: sykefravarsstatistikk-api

  vault:
    enabled: true

  kafka:
    pool: nav-prod
  resources:
    limits:
      memory: 64Gi
      cpu: 4000m
    requests:
      memory: 500Mi
      cpu: 200m
