apiVersion: kafka.nais.io/v1
kind: Topic
metadata:
  annotations:
    kafka.nais.io/removeDataWhenResourceIsDeleted: "true"
  name: sykefravarsstatistikk-v1
  namespace: arbeidsgiver
  labels:
    team: arbeidsgiver
spec:
  pool: nav-dev
  config:  # optional; all fields are optional too; defaults shown
    cleanupPolicy: delete  # delete, compact
    minimumInSyncReplicas: 1
    partitions: 1
    replication: 3  # see min/max requirements
    retentionBytes: -1
    retentionHours: 168 # one week
  acl:
    - team: arbeidsgiver
      application: sykefravarsstatistikk-api
      access: readwrite   # read, write, readwrite
    - team: teamcrm
      application: sf-sykefravaersstatistikk
      access: read
    - team: team-dialog
      application: sf-sykefravaersstatistikk
      access: read
