delete from sykefravar_statistikk_virksomhet_med_gradering where arstall < 2017;
delete from sykefravar_statistikk_virksomhet where arstall < 2017;
delete from sykefravar_statistikk_land where arstall < 2017;
delete from sykefravar_statistikk_sektor where arstall < 2017;
delete from sykefravar_statistikk_naring where arstall < 2017;
delete from sykefravar_statistikk_naring5siffer where arstall < 2017;
delete from sykefravar_statistikk_naring_med_varighet where arstall < 2017;
delete from virksomhet_metadata where arstall < 2017;
delete from virksomheter_bekreftet_eksportert where arstall < 2017;
