ALTER TABLE import_eksport_status
DROP COLUMN importert_statistikk
DROP COLUMN importert_virksomhetsdata
DROP COLUMN forberedt_neste_eksport
DROP COLUMN eksportert_paa_kafka
ADD COLUMN fullforte_jobber text not null;