name: Build, push & deploy

on: [ push ]

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}

concurrency:
  group: deploy-on-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Run tests
        run: mvn test
      # Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      # TODO: Fails with "HttpError: invalid json response body at https://api.github.com/repos/navikt/sykefravarsstatistikk-api/dependency-graph/snapshots reason: Unexpected end of JSON input"
      #- name: Update dependency graph
      #  uses: advanced-security/maven-dependency-submission-action@d682d5d68a398c90e9b35f8c564cd8e1918d6a24 # v3.0.1

  build-and-push-image:
    name: Build and push Docker image
    needs: test
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/fiks-prometheus-metrikker'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build jar with Maven
        run: mvn package -DskipTests
      - name: Login to GitHub Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push the Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}:latest,${{ env.IMAGE }}

  deploy-to-dev:
    name: Deploy to dev
    needs: build-and-push-image
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/fiks-prometheus-metrikker'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          VAR: version=${{ env.IMAGE }}
          RESOURCE: nais/dev.yaml

  deploy-to-prod:
    name: Deploy to prod
    needs: build-and-push-image
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          VAR: version=${{ env.IMAGE }}
          RESOURCE: nais/prod.yaml

  deployTopicsToDev:
    name: Deploy topics to dev
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/fiks-prometheus-metrikker'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy topics to dev-gcp
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: "nais/topics/topic-arbeidsgiver-sykefravaer-dev.yaml,nais/topics/topic-arbeidsgiver-sykefravarsstatistikk-land-dev.yaml,nais/topics/topic-arbeidsgiver-sykefravarsstatistikk-virksomhet-dev.yaml,nais/topics/topic-arbeidsgiver-sykefravarsstatistikk-naring-dev.yaml,nais/topics/topic-arbeidsgiver-sykefravarsstatistikk-sektor-dev.yaml,nais/topics/topic-arbeidsgiver-sykefravarsstatistikk-bransje-dev.yaml,nais/topics/topic-arbeidsgiver-sykefravarsstatistikk-metadata-virksomhet-dev.yaml"

  deployTopicsToProd:
    name: Deploy topics to prod
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy topics to prod-gcp
        uses: nais/deploy/actions/deploy@master
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-gcp
          RESOURCE: "nais/topics/topic-arbeidsgiver-sykefravaer-prod.yaml,nais/topics/topic-arbeidsgiver-sykefravarsstatistikk-land-prod.yaml,nais/topics/topic-arbeidsgiver-sykefravarsstatistikk-virksomhet-prod.yaml,nais/topics/topic-arbeidsgiver-sykefravarsstatistikk-naring-prod.yaml,nais/topics/topic-arbeidsgiver-sykefravarsstatistikk-sektor-prod.yaml,nais/topics/topic-arbeidsgiver-sykefravarsstatistikk-bransje-prod.yaml,nais/topics/topic-arbeidsgiver-sykefravarsstatistikk-metadata-virksomhet-prod.yaml"
