name: Deploy alerts
run-name: Deploy alerts ~~ "${{ github.event.head_commit.message }}"
on:
  push:
    paths:
      - 'nais/alerts.yaml'
      - '.github/workflows/deploy-alerts.yaml'
jobs:
  apply-alerts:
    name: Deploy alerts
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Deploy alerts to dev-fss
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-fss
          RESOURCE: nais/alerts.yaml
      - name: Deploy alerts to prod-fss
        if: github.ref == 'refs/heads/master'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: nais/alerts.yaml